### ISSUE TITLE
Sidebar with turbolinks 

### ISSUE THREAD

**Issue by MFProduction** [frontted/hero-rails#1]
Hi, I cannot get sidebar to work with turbolinks 5. It loads on inital page, but if i add a link and click on it sidebar disappears. Do you know how can this be solved?

**Comment by adriandemian** [comment]
Add this to your javascript:

`
document.addEventListener("turbolinks:load", function() {
  domFactory.handler.upgradeAll();
})
`

**Comment by MFProduction** [comment]
Thank you, that worked as expected. And thank you for quick response.
